SET SERVEROUTPUT ON;
DECLARE
    v_count NUMBER;
BEGIN
    -- Check if the user already exists using ALL_USERS instead of DBA_USERS
    SELECT COUNT(*) INTO v_count
    FROM all_users
    WHERE username = UPPER('APPADMIN');

    IF v_count > 0 THEN
        -- Drop the user if it already exists
        EXECUTE IMMEDIATE 'DROP USER APPADMIN CASCADE';
        DBMS_OUTPUT.PUT_LINE('Existing user APPADMIN dropped.');
    END IF;

    -- Create the user
    EXECUTE IMMEDIATE 'CREATE USER APPADMIN IDENTIFIED BY Northeastern2024';
    DBMS_OUTPUT.PUT_LINE('User created successfully.');

    -- Grant permissions to the user
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO APPADMIN';
    EXECUTE IMMEDIATE 'ALTER USER APPADMIN QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT ALTER ANY TABLE TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT DROP ANY TABLE TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT INSERT ANY TABLE TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT UPDATE ANY TABLE TO APPADMIN';
    EXECUTE IMMEDIATE 'GRANT DELETE ANY TABLE TO APPADMIN';

    -- Commit the changes
    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Permissions granted and changes committed successfully.');

END;
/
